---
title: CV
format:
  quarto-cv-pdf: default
author: Salvatore Cayabyab
date: last-modified
# phone: 123-456-7890
# address: "Guinness Brewery · Park Royal · London NW10 7RR, UK"
email: salvatorecayabyab@gmail.com
fontsize: 11pt

github: scayabyab # github account
# orcid: 0000-0002-1825-0097 # orcid identifier
# web: quarto.org
fontawesome: yes
nocite: '@*'

validate-yaml: false
csl: apa-cv.csl
---

# Education

**University of California, Los Angeles**  \hfill 2024-Current \newline
*B.A. Statistics and Data Science*
\vfill



# Skills
**Programming & Tools:** Computational Statistics with R • Object-Oriented Programming in C++

**Statistical Methods:** Data Analysis and Regression • Design and Analysis of Experiments •
Statistical Models

**Mathematics & Optimization:** Linear Algebra • Computation and Optimization • Monte Carlo
Methods • Data Mining
\vfill

# Projects

**C++ Robotics Project** — Designed and implemented a robot using C++ to execute sensor-based
movement and decision logic.


\vfill

# Employment

Starbucks Coffee Company - *Shift Supervisor* \hfill April 2022 - Sept. 2024

• Led a diverse team to ensure smooth, efficient daily operations in a fast-paced environment. \newline
• Fostered strong collaboration and communication among team members to maintain
consistent service quality. \newline
• Trained and mentored new employees, promoting a supportive and growth-oriented
workplace culture. \newline
• Coordinated with management to implement workflow improvements and enhance team
productivity.\newline

\vfill


